buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        // Only used if app/google-services.json is present.
        classpath 'com.google.gms:google-services:4.4.2'
        implementation(platform("com.google.firebase:firebase-bom:34.13.0"))
        implementation("com.google.firebase:firebase-analytics")
    }
}

plugins {
    id("com.android.application")
    id("com.google.gms.google-services")
    id 'com.android.application' version '8.7.3' apply false
    id("com.google.gms.google-services") version "4.4.4" apply false
}
